Add possibility configure path cookie
ezsystems/EzSystemsPrivacyCookieBundle pull request #18
Opened 2017-02-27 13:11 UTC by anijra

2017-02-27 13:25 UTC, clash82 commented
@anijra could you please revert files permission change?

2017-02-27 14:54 UTC, clash82 requested changes
Good work, some small improvements submitted

2017-02-27 14:54 UTC, clash82 commented on DependencyInjection/Configuration.php
> +                ->integerNode('path')
AFAIK this is a `scalarNode`

would be great if you could also provide some details using `info` key

2017-02-27 14:54 UTC, clash82 commented on README.md
> +cookiePath       | null                                           | Specifies the cookie path
We could add some context here:

` Specifies the cookie path (by default cookie will be available only for the current domain)`

2017-02-27 14:54 UTC, clash82 commented on Resources/config/default_settings.yml
> +    # Specifies the cookie path
please, use lowercase to be consistent with rest of the comments here ;)

2017-02-27 14:54 UTC, clash82 commented on Resources/public/js/privacycookie.js
> +        if(path) {
CS: `if (path) {`

2017-02-27 15:39 UTC, clash82 approved these changes

2017-02-27 15:47 UTC, damianz5 approved these changes

2017-02-28 06:18 UTC, andrerom commented
Still some chmod changes here!

2017-02-28 18:14 UTC, clash82 commented
@anijra two files are still waiting for permissions change

2017-03-01 12:06 UTC, SylvainGuittard approved these changes
Thank you @anijra for the contribution

2017-03-02 02:18 UTC, SylvainGuittard commented
@anijra could you please rebase your PR in order to have just one commit. I will merge it after.

2017-03-02 12:52 UTC, merged

2017-03-02 13:42 UTC, clash82 commented
@SylvainGuittard please, don't forget to create a net version tag.